(()=>{
  const tabs=document.getElementById('tabs'),feed=document.getElementById('feed');if(!tabs||!feed)return;
  const C={g:'#15803d',y:'#b45309',r:'#b91c1c',b:'#2563eb',p:'#7c3aed',c:'#0891b2'};
  const labels={top:'Top Stories',nfl:'NFL',x:'X',underreported:'Underreported',world:'World',us:'US',presidential:'Presidential',federal:'Federal',legislation:'Legislation',nm:'New Mexico',local:'Local',region:'Region',technology:'Technology',gaming:'Gaming',military:'Military',entertainment:'Entertainment'};
  let busy=false,last='';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const age=ms=>{const m=Math.max(0,Math.round(ms/60000));if(m<60)return`${m}m`;const h=Math.floor(m/60);return h<24?`${h}h ${m%60}m`:`${Math.floor(h/24)}d ${h%24}h`};
  const active=()=>tabs.querySelector('.tab[data-category="admin"][aria-selected="true"]');
  const dot=(s)=>`<span style="width:9px;height:9px;border-radius:50%;background:${s==='green'?C.g:s==='yellow'?C.y:C.r};box-shadow:0 0 0 4px ${s==='green'?'rgba(21,128,61,.10)':s==='yellow'?'rgba(180,83,9,.10)':'rgba(185,28,28,.10)'};flex:0 0 auto"></span>`;
  const card=(t,v,sub,color)=>`<div style="background:var(--surface);border:1px solid var(--line);border-radius:16px;padding:12px;box-shadow:0 8px 22px rgba(15,23,42,.07)"><div style="font-size:.56rem;font-weight:950;letter-spacing:.08em;color:var(--muted);text-transform:uppercase">${esc(t)}</div><div style="font-size:1.3rem;font-weight:950;color:${color};margin:7px 0 4px">${esc(v)}</div><div style="font-size:.61rem;color:var(--muted)">${esc(sub)}</div></div>`;
  const section=(t,s,h)=>`<section style="display:grid;gap:8px"><div><div style="font-size:.7rem;font-weight:950">${t}</div><div style="font-size:.6rem;color:var(--muted);margin-top:2px">${s}</div></div>${h}</section>`;
  async function json(path){const t=performance.now();try{const r=await fetch(`${path}?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status}`);return{ok:true,ms:Math.round(performance.now()-t),data:await r.json()}}catch(e){return{ok:false,ms:Math.round(performance.now()-t),error:String(e.message||e)}}}
  async function github(){const t=performance.now();try{const r=await fetch('https://api.github.com/repos/battleatom/News/actions/workflows/pages-build-deployment/runs?per_page=1',{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));const run=(await r.json()).workflow_runs?.[0];return{ok:!!run,ms:Math.round(performance.now()-t),run}}catch(e){return{ok:false,ms:Math.round(performance.now()-t),error:String(e.message||e)}}}
  async function weather(){let loc=null;try{loc=JSON.parse(localStorage.getItem('underreported-v6-location')||'null')}catch{};if(!loc?.lat||!loc?.lon)return{ok:false,waiting:true,ms:0};const t=performance.now();try{const q=new URLSearchParams({latitude:String(loc.lat),longitude:String(loc.lon),current:'temperature_2m',forecast_days:'1'}),r=await fetch(`https://api.open-meteo.com/v1/forecast?${q}`,{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));await r.json();return{ok:true,ms:Math.round(performance.now()-t)}}catch(e){return{ok:false,ms:Math.round(performance.now()-t),error:String(e.message||e)}}}
  function apiRow(name,state,detail){return`<div style="display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:9px;align-items:center;padding:9px 0;border-top:1px solid var(--line)">${dot(state)}<div><div style="font-size:.65rem;font-weight:900">${esc(name)}</div><div style="font-size:.56rem;color:var(--muted);margin-top:2px">${esc(detail)}</div></div><strong style="font-size:.58rem;color:${state==='green'?C.g:state==='yellow'?C.y:C.r}">${state.toUpperCase()}</strong></div>`}
  function stateFor(check){if(check.waiting)return'yellow';if(!check.ok)return'red';return check.ms>1800?'yellow':'green'}
  async function render(){if(!active()||busy)return;busy=true;try{
    const [st,fd,nf,mk,bx,gh,wx]=await Promise.all([json('status.json'),json('feed.json'),json('nfl.json'),json('markets.json'),json('boxoffice.json'),github(),weather()]);
    const status=st.data||{},feedData=fd.data||{},now=Date.now();
    const all=[];for(const [cat,arr] of Object.entries(feedData.stories||{}))for(const s of arr||[])all.push({...s,category:cat});
    const pub=s=>Date.parse(s.published_at||s.publishedAt||s.date||'')||0;
    const last1=all.filter(s=>pub(s)&&now-pub(s)<=3600000).length,last6=all.filter(s=>pub(s)&&now-pub(s)<=21600000).length,last24=all.filter(s=>pub(s)&&now-pub(s)<=86400000).length;
    const fresh=[];for(const [cat,arr] of Object.entries(feedData.stories||{})){const newest=Math.max(0,...(arr||[]).map(pub));fresh.push({cat,count:(arr||[]).length,age:newest?now-newest:Infinity})}fresh.sort((a,b)=>b.age-a.age);
    const sourceRows=status.sourceStatuses||[],failed=sourceRows.filter(x=>x.status!=='live'||x.error),zero=sourceRows.filter(x=>Number(x.storyCount||0)===0),stale=fresh.filter(x=>x.cat!=='boxoffice'&&x.age>6*3600000);
    const attention=[...failed.slice(0,3).map(x=>({c:C.r,t:`${x.name||x.id} · ${x.error||'source unavailable'}`})),...stale.slice(0,3).map(x=>({c:C.y,t:`${labels[x.cat]||x.cat} · newest story ${age(x.age)} old`})),...zero.slice(0,2).map(x=>({c:C.y,t:`${x.name||x.id} · 0 stories returned`}))];
    const fb=status.feedbackPoolCounts||{},pool=Number(status.poolStoryCount||0),visible=Number(status.storyCount||0),supp=Math.max(0,pool-visible),rate=pool?supp/pool:0;
    const attentionHtml=attention.length?`<div style="display:grid;gap:6px">${attention.map(a=>`<div style="padding:9px 10px;border-radius:12px;border:1px solid color-mix(in srgb,${a.c} 22%,var(--line));background:color-mix(in srgb,${a.c} 6%,var(--surface));font-size:.63rem">${esc(a.t)}</div>`).join('')}</div>`:`<div style="padding:10px;border-radius:12px;background:rgba(21,128,61,.06);border:1px solid rgba(21,128,61,.18);color:${C.g};font-size:.64rem;font-weight:900">✓ Nothing needs attention right now.</div>`;
    const apiRows=[];
    apiRows.push(apiRow('Feed API',stateFor(fd),fd.ok?`${fd.ms} ms · ${visible||all.length} published stories`:`Unavailable · ${fd.error||'request failed'}`));
    apiRows.push(apiRow('Status API',stateFor(st),st.ok?`${st.ms} ms · ${status.healthySourceCount||0}/${status.sourceCount||0} sources healthy`:`Unavailable · ${st.error||'request failed'}`));
    const nfState=!nf.ok?'red':nf.data?.error?'yellow':stateFor(nf);apiRows.push(apiRow('NFL Data',nfState,nf.ok?(nf.data?.error||`${nf.ms} ms · ${(nf.data?.games||[]).length} games`):`Unavailable · ${nf.error}`));
    const mkState=!mk.ok?'red':mk.data?.error?'yellow':stateFor(mk);apiRows.push(apiRow('Markets / Alpha Vantage',mkState,mk.ok?(mk.data?.error||`${mk.ms} ms · ${(mk.data?.markets||[]).length} instruments`):`Unavailable · ${mk.error}`));
    const bxState=!bx.ok?'red':bx.data?.error?'yellow':stateFor(bx);apiRows.push(apiRow('Box Office / TMDB',bxState,bx.ok?(bx.data?.error||`${bx.ms} ms · ${(bx.data?.movies||[]).length} movies`):`Unavailable · ${bx.error}`));
    apiRows.push(apiRow('Open-Meteo Weather',stateFor(wx),wx.waiting?'Waiting for saved location':wx.ok?`${wx.ms} ms · live response`:`Unavailable · ${wx.error}`));
    const supaState=status.feedbackEnforcement==='server'?'green':'yellow';apiRows.push(apiRow('Supabase Feedback',supaState,status.feedbackEnforcement==='server'?`Server enforcement active · D ${fb.D||0} · NR ${fb.NR||0} · NW ${fb.NW||0}`:'Server enforcement not confirmed'));
    let ghState='red',ghDetail=gh.error||'Unavailable';if(gh.ok&&gh.run){ghState=gh.run.status==='completed'&&gh.run.conclusion==='success'?'green':gh.run.status==='in_progress'?'yellow':'red';ghDetail=`${gh.run.status}${gh.run.conclusion?` / ${gh.run.conclusion}`:''} · ${String(gh.run.head_sha||'').slice(0,7)} · ${gh.ms} ms`}apiRows.push(apiRow('GitHub Pages',ghState,ghDetail));
    const freshness=`<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(118px,1fr));gap:8px">${fresh.filter(x=>x.cat!=='boxoffice').map(x=>{const c=x.age<=2*3600000?C.g:x.age<=6*3600000?C.b:x.age<=12*3600000?C.y:C.r;return`<div style="padding:10px;border:1px solid var(--line);border-radius:13px;background:var(--surface)"><div style="display:flex;justify-content:space-between;gap:6px"><strong style="font-size:.62rem">${esc(labels[x.cat]||x.cat)}</strong><span style="width:8px;height:8px;border-radius:50%;background:${c}"></span></div><div style="font-size:.88rem;font-weight:950;color:${c};margin-top:5px">${Number.isFinite(x.age)?age(x.age):'—'}</div><div style="font-size:.55rem;color:var(--muted)">${x.count} stories · newest</div></div>`}).join('')}</div>`;
    const html=`<div id="admin-live-ops" style="display:grid;gap:15px;margin-top:14px">${section('API & Service Status','Green = healthy · Yellow = degraded/slow/stale · Red = unavailable/error.',`<div style="display:grid;gap:0">${apiRows.join('')}</div>`)}${section('Needs Attention','Only active warnings are shown here.',attentionHtml)}${section('Live Activity','Current publishing, suppression and feedback activity.',`<div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px">${card('Last hour',last1,'new stories',C.g)}${card('Last 6 hours',last6,'new stories',C.b)}${card('Last 24 hours',last24,'new stories',C.p)}</div><div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px">${card('Suppressed',supp,`${(rate*100).toFixed(1)}% of pool`,rate>.2?C.y:C.c)}${card('Feedback',(fb.D||0)+(fb.NR||0)+(fb.NW||0),`D ${fb.D||0} · NR ${fb.NR||0} · NW ${fb.NW||0}`,C.y)}${card('Reserve',status.reserveStoryCount||0,'standby stories',C.c)}</div>`)}${section('Content Freshness','Age of the newest story in each category.',freshness)}</div>`;
    const key=`${status.generatedAt||''}|${gh.run?.head_sha||''}|${visible}|${last1}`;if(key!==last||!document.getElementById('admin-live-ops')){last=key;document.getElementById('admin-live-ops')?.remove();const wrap=feed.firstElementChild;if(wrap)wrap.insertAdjacentHTML('beforeend',html)}
  }catch(e){console.warn('Admin live ops unavailable',e)}finally{busy=false}}
  function schedule(){if(active())setTimeout(render,60)}
  new MutationObserver(schedule).observe(tabs,{subtree:true,attributes:true,attributeFilter:['aria-selected'],childList:true});new MutationObserver(schedule).observe(feed,{childList:true,subtree:false});tabs.addEventListener('click',e=>{if(e.target.closest('.tab[data-category="admin"]'))setTimeout(render,120)},true);document.addEventListener('v6:tabchange',e=>{if(e.detail?.category==='admin')schedule()});document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule()});setInterval(()=>{if(active())render()},30000);
})();