(()=>{'use strict';
const tabs=document.getElementById('tabs'),feed=document.getElementById('feed');if(!tabs||!feed)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(method='GET',body){const r=await fetch('/api/feedback',{method,cache:'no-store',headers:{Accept:'application/json','Content-Type':'application/json',...(window.DPoolSecurity?.headers?.()||{})},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||('DPool request failed '+r.status));return d}
function active(){return !!tabs.querySelector('.tab[data-category="admin"][aria-selected="true"]')}
function recordKey(r){return encodeURIComponent(JSON.stringify({reason:r.reason,category:r.category,title:r.title,url:r.url,source:r.source,original_category:r.original_category}))}
function card(r){const st=r.review?.status||'delete',label=st==='safe'?'SAFE':st==='restore'?'RESTORE':'DELETE';return '<article class="dpool-review-card" data-record="'+recordKey(r)+'"><div class="dpool-review-top"><span class="dpool-review-flag '+st+'">'+label+'</span><span class="dpool-reason">'+esc(r.reason)+'</span></div><h4>'+esc(r.title||'(untitled)')+'</h4><div class="dpool-meta">'+esc(r.source||'Unknown source')+' · '+esc(r.category||'unknown')+'</div><p>'+esc(r.review?.reason||'No review note.')+'</p><div class="dpool-card-actions"><button type="button" data-action="restore">Restore</button><button type="button" data-action="delete" class="danger">Delete</button></div></article>'}
function close(){feed.querySelector('#dpool-inline-list')?.remove();feed.querySelectorAll('[data-admin-pool].active').forEach(x=>x.classList.remove('active'))}
async function show(reason,d,button){close();button.classList.add('active');const section=button.closest('div')?.parentElement||button.parentElement;const list=document.createElement('div');list.id='dpool-inline-list';list.className='dpool-list';const rows=d.pools?.[reason]||[];list.innerHTML=rows.length?rows.map(card).join(''):'<p class="dpool-empty">This pool is empty.</p>';section.after(list);list.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{const c=b.closest('.dpool-review-card'),rec=JSON.parse(decodeURIComponent(c.dataset.record)),action=b.dataset.action;if(!confirm(action==='delete'?'Delete this DPool record?':'Restore this article and remove its DPool suppression?'))return;const auth=await window.DPoolSecurity?.requireAuth?.();if(!auth)return;b.disabled=true;try{await api('DELETE',{...rec,action});const fresh=await api();await show(reason,fresh,button)}catch(e){alert(e.message);b.disabled=false}})}
feed.addEventListener('click',async e=>{const button=e.target.closest('[data-admin-pool]');if(!button||!active())return;const reason=button.dataset.adminPool;if(button.classList.contains('active')){close();return}const auth=await window.DPoolSecurity?.requireAuth?.();if(!auth)return;try{const d=await api();await show(reason,d,button)}catch(err){alert(err.message)}});
new MutationObserver(()=>{if(active()&&!feed.querySelector('[data-admin-pool]'))close()}).observe(feed,{childList:true,subtree:false});
})();