(()=>{'use strict';const tabs=document.getElementById('tabs'),feed=document.getElementById('feed');if(!tabs||!feed)return;let mounted=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(method='GET',body){const r=await fetch('/api/feedback',{method,cache:'no-store',headers:{Accept:'application/json','Content-Type':'application/json',...(window.DPoolSecurity?.headers?.()||{})},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||('DPool request failed '+r.status));return d}
function active(){return !!tabs.querySelector('.tab[data-category="admin"][aria-selected="true"]')}
function shell(){let x=feed.querySelector('#dpool-manager');if(x)return x;x=document.createElement('section');x.id='dpool-manager';x.className='dpool-manager';const host=feed.firstElementChild||feed;host.prepend(x);return x}
function recordKey(r){return encodeURIComponent(JSON.stringify({reason:r.reason,category:r.category,title:r.title,url:r.url,source:r.source,original_category:r.original_category}))}
function card(r){const st=r.review?.status||'delete',label=st==='safe'?'SAFE':st==='restore'?'RESTORE':'DELETE';return '<article class="dpool-review-card" data-record="'+recordKey(r)+'"><div class="dpool-review-top"><span class="dpool-review-flag '+st+'">'+label+'</span><span class="dpool-reason">'+esc(r.reason)+'</span></div><h4>'+esc(r.title||'(untitled)')+'</h4><div class="dpool-meta">'+esc(r.source||'Unknown source')+' · '+esc(r.category||'unknown')+'</div><p>'+esc(r.review?.reason||'No review note.')+'</p><div class="dpool-card-actions"><button type="button" data-action="restore">Restore</button><button type="button" data-action="delete" class="danger">Delete</button></div></article>'}
async function render(selected=''){if(!active())return;const root=shell();const counts={D:0,NR:0,NW:0};root.innerHTML='<div class="dpool-head"><div><strong>DPool Manager</strong><small>PIN protected · review learned feedback records</small></div><div class="dpool-tabs">'+['D','NR','NW'].map(k=>'<button type="button" data-pool="'+k+'">'+k+' <b>'+Number(counts[k]||0)+'</b></button>').join('')+'</div></div><div class="dpool-list"><p class="dpool-empty">Select D, NR, or NW to review its articles.</p></div>';root.querySelectorAll('[data-pool]').forEach(b=>b.onclick=async()=>{const auth=await window.DPoolSecurity?.requireAuth?.();if(!auth)return;try{const d=await api();await show(b.dataset.pool,d)}catch(e){alert(e.message)}});if(selected){const auth=await window.DPoolSecurity?.requireAuth?.();if(auth){const d=await api();await show(selected,d)}}mounted=true}
function show(reason,d){const root=shell();root.querySelectorAll('[data-pool]').forEach(b=>b.classList.toggle('active',b.dataset.pool===reason));const rows=d.pools?.[reason]||[],list=root.querySelector('.dpool-list');list.innerHTML=rows.length?rows.map(card).join(''):'<p class="dpool-empty">This pool is empty.</p>';list.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{const c=b.closest('.dpool-review-card'),rec=JSON.parse(decodeURIComponent(c.dataset.record)),action=b.dataset.action;if(!confirm(action==='delete'?'Delete this DPool record?':'Restore this article and remove its DPool suppression?'))return;const auth=await window.DPoolSecurity?.requireAuth?.();if(!auth)return;b.disabled=true;try{await api('DELETE',{...rec,action});await window.UnderreportedFeedback?.refresh?.();await render(reason)}catch(e){alert(e.message);b.disabled=false}})}
tabs.addEventListener('click',e=>{if(e.target.closest('.tab[data-category="admin"]'))setTimeout(()=>render(),220)},true);document.addEventListener('v6:tabchange',e=>{if(e.detail?.category==='admin')setTimeout(()=>render(),100)});if(active())setTimeout(()=>render(),300);
})();