const CACHE_KEY="underreported-v6-location",MAX_AGE=6*60*60*1000;
const REGION_BY_STATE={AZ:"southwest",NM:"southwest",CO:"mountain",UT:"mountain",NV:"west",CA:"west",OR:"pacific-northwest",WA:"pacific-northwest",ID:"mountain",MT:"mountain",WY:"mountain",TX:"south",OK:"south",AR:"south",LA:"south",TN:"south",KY:"south",VA:"south",WV:"south",IL:"midwest",MI:"midwest",OH:"midwest",WI:"midwest",MN:"midwest",IA:"midwest",MO:"midwest",IN:"midwest",NY:"northeast",PA:"northeast",NJ:"northeast",CT:"northeast",MA:"northeast",ME:"northeast",NH:"northeast",VT:"northeast",RI:"northeast",FL:"southeast",GA:"southeast",AL:"southeast",SC:"southeast",NC:"southeast",MS:"southeast",AK:"pacific-northwest"};
function cached(){try{const value=JSON.parse(localStorage.getItem(CACHE_KEY)||"null");if(value&&Date.now()-Number(value.savedAt||0)<MAX_AGE)return value}catch{}return null}
function save(value){const state=String(value.state||"").replace(/^US-/,"").toUpperCase(),out={...value,state,region:REGION_BY_STATE[state]||"",savedAt:Date.now()};try{localStorage.setItem(CACHE_KEY,JSON.stringify(out))}catch{}return out}
function deviceCoords(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error("geolocation unavailable"));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy,source:"device"}),reject,{enableHighAccuracy:false,maximumAge:15*60*1000,timeout:5500})})}
function countyFromReverse(d){const direct=String(d.county||d.countyName||"").trim();if(direct)return direct;const admin=Array.isArray(d.localityInfo?.administrative)?d.localityInfo.administrative:[];return admin.map(x=>String(x?.name||"").trim()).find(n=>/(county|parish|borough|census area|municipality)$/i.test(n))||""}
async function reverse(coords){const q=new URLSearchParams({latitude:String(coords.lat),longitude:String(coords.lon),localityLanguage:"en"}),response=await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?${q}`,{cache:"no-store"});if(!response.ok)throw new Error("reverse geocode unavailable");const data=await response.json();return{...coords,city:data.city||data.locality||"",state:String(data.principalSubdivisionCode||"").replace(/^US-/,""),county:countyFromReverse(data)}}
async function ip(){const response=await fetch("https://ipapi.co/json/",{cache:"no-store"});if(!response.ok)throw new Error("ip location unavailable");const data=await response.json();return{lat:Number(data.latitude),lon:Number(data.longitude),city:data.city||"",state:data.region_code||"",county:"",source:"ip"}}
export function clearLocation(){try{localStorage.removeItem(CACHE_KEY)}catch{}}
export async function resolveLocation(options={}){if(!options.force){const prior=cached();if(prior)return prior}try{return save(await reverse(await deviceCoords()))}catch{try{return save(await ip())}catch{return null}}}
