import{Store}from"./store.js";
import{renderActive,esc}from"./renderers.js";
import{resolveLocation,clearLocation}from"./location.js";
import{loadPools,submitFeedback}from"./feedback.js";
const store=new Store(),tabs=document.getElementById("tabs"),root=document.getElementById("feed"),health=document.getElementById("health"),localDate=document.getElementById("local-date"),localTime=document.getElementById("local-time"),locationButton=document.getElementById("location-button"),weatherStatus=document.getElementById("weather-status"),refreshStatus=document.getElementById("refresh-status"),marketsRoot=document.getElementById("markets"),toast=document.getElementById("toast");
const ICONS={top:"◆",nfl:"🏈",x:"𝕏",underreported:"◈",world:"🌐",us:"🇺🇸",presidential:"🏛",federal:"⚖",legislation:"📜",nm:"☀",local:"⌖",region:"◫",technology:"⌘",gaming:"🎮",military:"★",entertainment:"🎭",boxoffice:"🎬",bookmarks:"★"};
const X_TOPICS=[["x-health","Health"],["x-technology","Technology & AI"],["x-celebrities","Celebrities & Public Figures"],["x-world","World"],["x-politics","Politics & Government"],["x-entertainment","Entertainment"],["x-sports","Sports"],["x-business","Business & Economy"],["x-gaming","Gaming"],["x-science","Science"]];
let nextCheck=Date.now()+60000,refreshing=false,lastWeatherAt=0,nflRefreshing=false;
async function json(path){const response=await fetch(`${path}?ts=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error(`${path} ${response.status}`);return response.json()}
function showToast(message){toast.textContent=message;toast.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>{toast.hidden=true},2200)}
function renderTabs(){tabs.innerHTML="";const defs=[...Object.entries(store.feed.categories),["bookmarks",{label:"Bookmarks"}]];for(const[key,meta]of defs){const button=document.createElement("button");button.type="button";button.className="tab";button.dataset.category=key;button.setAttribute("role","tab");button.setAttribute("aria-selected",String(key===store.active));button.setAttribute("aria-current",key===store.active?"page":"false");const count=key==="nfl"?(store.nfl.games?.length||0):key==="boxoffice"?(store.boxoffice.movies?.length||0):key==="bookmarks"?store.bookmarks.length:(store.feed.stories?.[key]?.length||0);button.innerHTML=`<span aria-hidden="true">${ICONS[key]||"•"}</span><span>${meta.label}</span><small>${count}</small>`;tabs.appendChild(button)}}
function renderMarkets(){const rows=store.markets?.markets||[],generated=store.markets?.generatedAt||"";const formatPrice=row=>{const value=Number(row.price||0),label=String(row.label||row.symbol||"").toUpperCase();if(label==="VIX"||label==="10Y")return value.toFixed(2);if(label==="WTI OIL"||label==="GOLD")return`$${value.toFixed(2)}`;return value.toLocaleString(undefined,{maximumFractionDigits:2})};const items=rows.map(row=>{const pct=Number(row.changePct||0),cls=pct>0?"up":pct<0?"down":"flat",arrow=pct>0?"▲":pct<0?"▼":"—";return `<span class="market"><span class="market-name">${row.label||row.symbol}</span><span class="market-value">${formatPrice(row)}</span><span class="${cls}">${arrow} ${Math.abs(pct).toFixed(2)}%</span></span>`}).join("");const benchmark=rows.find(row=>row.symbol==="^GSPC")||rows[0],closed=/closed/i.test(String(benchmark?.marketState||"")),dt=new Date(generated),stamp=Number.isNaN(dt.getTime())?"":new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(dt),status=`${closed?"MARKETS CLOSED":"MARKET DATA"}${stamp?` · ${stamp}`:""}`;marketsRoot.innerHTML=`<div class="markets-track"><span class="market-label">MARKETS</span>${items||'<span class="market-note">Markets unavailable</span>'}<span class="market"><span class="market-name">OPEC</span><span class="flat">WATCH</span></span><span class="market-time">${status}</span></div>`}
function xAgeBand(value){const ts=Date.parse(value||"");if(!Number.isFinite(ts))return"";const days=Math.max(0,(Date.now()-ts)/86400000);return days<=2?"blue":days<=4?"green":days<=7?"orange":days<=10?"purple":"red"}
function xCard(story,topic,index){const related=store.allStories().filter(other=>other.id!==story.id&&other.category!=="x").filter(other=>{const a=new Set(String(story.title||"").toLowerCase().match(/[a-z0-9]{4,}/g)||[]),b=new Set(String(other.title||"").toLowerCase().match(/[a-z0-9]{4,}/g)||[]);return[...a].filter(word=>b.has(word)).length>=2}).slice(0,3);const evidence=related.length?`<div class="related"><summary style="list-style:none;cursor:default;color:var(--text)">REPORTING & EVIDENCE</summary>${related.map((item,i)=>`<a href="${esc(item.url)}" target="_blank" rel="noopener noreferrer">${i+1}. ${esc(item.title)} <span>· ${esc(item.source)}</span></a>`).join("")}</div>`:"";const band=xAgeBand(story.published_at);return `<article class="story-card ${band?`age-${band}`:""}" data-story-id="${esc(story.id)}" data-category="x"><div class="card-topline"><span class="category-pill">${esc(topic)}</span><span class="signal">TOP X CONVERSATION</span><button class="bookmark-btn ${store.isBookmarked(story.id)?"saved":""}" type="button" data-bookmark="${esc(story.id)}" aria-label="Save bookmark">${store.isBookmarked(story.id)?"★":"☆"}</button></div><h3><a href="${esc(story.url)}" target="_blank" rel="noopener noreferrer">${index+1}. ${esc(story.title)}</a></h3>${story.summary?`<p class="story-why"><strong>WHAT'S HAPPENING</strong><span>${esc(story.summary)}</span></p>`:""}<p class="story-why"><strong>WHY IT'S TRENDING</strong><span>This is the strongest current conversation found for the ${esc(topic)} slot using current public-discussion and news signals.</span></p><p class="story-why"><strong>WHAT PEOPLE ARE SAYING</strong><span>The conversation includes multiple reactions and interpretations. Discussion volume does not by itself verify claims circulating on X.</span></p><p class="story-why"><strong>✓ WHAT'S CONFIRMED</strong><span>The linked reporting confirms the underlying news development. Claims beyond that reporting should be treated as unverified until independently supported.</span></p>${evidence}<div class="story-meta" style="margin-top:9px">${esc(new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(story.published_at)))}${story.source?` · ${esc(story.source)}`:""}</div><div class="feedback-controls" role="group" aria-label="Article feedback"><button type="button" data-feedback="D">D · Duplicate</button><button type="button" data-feedback="NR">NR · Not Relevant</button><button type="button" data-feedback="NW">NW · Not Wanted</button></div></article>`}
function renderX(){const all=store.categoryStories("x"),bySource=new Map(all.map(story=>[story.source_id,story])),rows=X_TOPICS.map(([id,topic])=>({topic,story:bySource.get(id)})).filter(row=>row.story);root.innerHTML=`<div class="section-head"><div><h2>𝕏 What's Trending</h2><p class="section-intro">Ten fixed topic slots surface one current conversation each. Public discussion identifies the conversation; independent reporting provides the explanation. A conversation is not proof of a claim.</p></div><div class="section-stats"><span>${rows.length} of ${X_TOPICS.length}</span></div></div><div class="story-list">${rows.map((row,i)=>xCard(row.story,row.topic,i)).join("")}</div>${rows.length?"":'<div class="empty">No X conversations met the publication requirements right now.</div>'}`}
function render(){renderTabs();renderMarkets();document.body.dataset.activeTab=store.active;if(store.active==="x")renderX();else renderActive({store,root});const activeTab=tabs.querySelector('[aria-selected="true"]');if(activeTab&&innerWidth<=760)requestAnimationFrame(()=>activeTab.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"}))}
function findStory(id,category){return store.storyById(id)||(store.feed.stories?.[category]||[]).find(story=>story.id===id)}
function beep(){try{const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;const ctx=new AudioCtx(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=520;gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.06,ctx.currentTime+.01);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.12);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.13)}catch{}}
function updateClock(){const now=new Date();localDate.textContent=new Intl.DateTimeFormat(undefined,{weekday:"short",month:"short",day:"numeric"}).format(now);localTime.textContent=new Intl.DateTimeFormat(undefined,{hour:"numeric",minute:"2-digit",second:"2-digit"}).format(now);const seconds=Math.max(0,Math.ceil((nextCheck-Date.now())/1000)),m=Math.floor(seconds/60),s=seconds%60;const base=store.status?.storyCount!=null?`${store.status.storyCount} stories`:"Feed ready";refreshStatus.textContent=`${refreshing?"Checking":"Auto update"} · ${base} · ${m}:${String(s).padStart(2,"0")}`}
async function updateWeather(force=false){if(!store.location?.lat||!store.location?.lon)return;if(!force&&Date.now()-lastWeatherAt<15*60*1000)return;lastWeatherAt=Date.now();try{const q=new URLSearchParams({latitude:store.location.lat,longitude:store.location.lon,current:"temperature_2m,weather_code",temperature_unit:"fahrenheit",timezone:"auto"}),r=await fetch(`https://api.open-meteo.com/v1/forecast?${q}`,{cache:"no-store"});if(!r.ok)throw new Error("weather unavailable");const d=await r.json(),temp=Math.round(d.current?.temperature_2m),code=Number(d.current?.weather_code);const condition=code===0?"Clear":code<=3?"Cloudy":code<=48?"Fog":code<=67?"Rain":code<=77?"Snow":code<=82?"Showers":code<=99?"Storm":"";weatherStatus.textContent=Number.isFinite(temp)?`${temp}°F${condition?` · ${condition}`:""}`:""}catch{weatherStatus.textContent=""}}
async function setLocation(force=false){locationButton.textContent="Location: resolving…";if(force)clearLocation();store.location=await resolveLocation({force});locationButton.textContent=store.location?`Location: ${[store.location.city,store.location.state].filter(Boolean).join(", ")||"resolved"}`:"Location: unavailable";await updateWeather(true);if(["local","region","boxoffice"].includes(store.active))render()}
function nflGameKey(game){const teams=game.teams||[],away=teams.find(t=>t.homeAway==="away")||{},home=teams.find(t=>t.homeAway==="home")||{},ts=Date.parse(game.date||"");return `${away.abbr||""}|${home.abbr||""}|${Number.isFinite(ts)?Math.round(ts/600000):game.date||""}`}
function normalizeEspnGame(event){const competition=(event.competitions||[{}])[0],statusType=event.status?.type||{},teams=(competition.competitors||[]).map(comp=>{const team=comp.team||{};return{name:team.displayName||team.shortDisplayName||"",abbr:team.abbreviation||"",score:comp.score||"",homeAway:comp.homeAway||"",logo:team.logo||"",color:team.color||"",alternateColor:team.alternateColor||""}}),broadcasts=[...new Set((competition.broadcasts||[]).flatMap(x=>x.names||[]).filter(Boolean))],watch=(event.links||[]).find(x=>(x.rel||[]).some(r=>String(r).toLowerCase().includes("watch")));return{id:String(event.id||""),name:event.name||"",shortName:event.shortName||"",date:event.date||"",status:statusType.description||"",detail:statusType.shortDetail||statusType.detail||"",state:statusType.state||"",teams,broadcasts,watchUrl:watch?.href||"",venue:competition.venue?.fullName||"",plays:[]}}
async function livePlays(game){if(game.state!=="in"||!game.id)return game;try{const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/nfl/summary?event=${encodeURIComponent(game.id)}&ts=${Date.now()}`,{cache:"no-store"});if(!r.ok)return game;const d=await r.json();let plays=d.plays||[];if(!plays.length)plays=d.drives?.current?.plays||[];if(!plays.length)plays=(d.drives?.previous||[]).flatMap(x=>x.plays||[]);if(!plays.length)plays=d.scoringPlays||[];game.plays=plays.filter(p=>p&&(p.text||p.shortText)).slice(-4).map(p=>({clock:typeof p.clock==="object"?(p.clock?.displayValue||""):(p.clock||""),period:typeof p.period==="object"?(p.period?.number||""):(p.period||""),text:p.text||p.shortText||""}))}catch{}return game}
async function refreshNflLive(){if(nflRefreshing||store.active!=="nfl"||document.hidden)return;nflRefreshing=true;try{const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?limit=64&ts=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`ESPN ${r.status}`);const d=await r.json(),live=await Promise.all((d.events||[]).map(event=>livePlays(normalizeEspnGame(event)))),merged=new Map();for(const game of store.nfl.games||[]){const key=nflGameKey(game);if(key)merged.set(key,game)}for(const game of live){const key=nflGameKey(game);if(key)merged.set(key,game)}store.nfl={...store.nfl,games:[...merged.values()],error:""};render()}catch(error){console.warn("NFL live refresh failed",error)}finally{nflRefreshing=false}}
async function loadData(first=false){const[feed,nfl,boxoffice,markets,status,pools]=await Promise.all([json("feed.json"),json("nfl.json"),json("boxoffice.json"),json("markets.json").catch(()=>({markets:[],error:""})),json("status.json"),first?loadPools():Promise.resolve(store.suppressed)]);const previous=new Set(store.allStories().map(x=>x.id));store.setFeed(feed);store.nfl=nfl;store.boxoffice=boxoffice;store.markets=markets;store.status=status;store.suppressed=pools;if(!first){store.newIds=new Set(store.allStories().filter(x=>!previous.has(x.id)).map(x=>x.id));if(store.newIds.size){beep();showToast(`${store.newIds.size} new stor${store.newIds.size===1?"y":"ies"} loaded`)}}health.textContent=status.collectorErrors?.length?`Degraded · ${status.collectorErrors.length} source errors`:"V6 · healthy";health.dataset.state=status.collectorErrors?.length?"warn":"ok";render()}
async function refreshIfChanged(){if(refreshing)return;refreshing=true;try{const latest=await json("status.json");if(latest.generatedAt&&latest.generatedAt!==store.status?.generatedAt)await loadData(false)}catch(error){console.warn("V6 refresh check failed",error);health.textContent="V6 · update delayed";health.dataset.state="warn"}finally{refreshing=false;nextCheck=Date.now()+60000;updateClock()}}
tabs.addEventListener("click",event=>{const button=event.target.closest("[data-category]");if(!button)return;store.setActive(button.dataset.category);store.resetPage();render();if(store.active==="nfl")refreshNflLive();window.scrollTo({top:0,behavior:"auto"})});
root.addEventListener("change",event=>{const select=event.target.closest('[data-underreported-sort]');if(!select)return;store.setUnderreportedSort(select.value);render()});
root.addEventListener("click",async event=>{const more=event.target.closest('[data-action="load-more"]');if(more){store.loadMore();render();return}const bm=event.target.closest("[data-bookmark]");if(bm){const story=findStory(bm.dataset.bookmark,bm.closest("[data-category]")?.dataset.category);if(story){const saved=store.toggleBookmark(story);showToast(saved?"Story bookmarked":"Bookmark removed");render()}return}const game=event.target.closest("[data-nfl-game]");if(game){store.selectedNfl=game.dataset.nflGame;render();return}const feedback=event.target.closest("[data-feedback]");if(!feedback)return;const card=feedback.closest("[data-story-id]");if(!card)return;const story=findStory(card.dataset.storyId,card.dataset.category);if(!story)return;const reason=feedback.dataset.feedback;card.querySelectorAll("[data-feedback]").forEach(btn=>btn.disabled=true);try{const entry=await submitFeedback(reason,story,card.dataset.category);store.suppressed.get(reason).push(entry);showToast(reason==="D"?"Duplicate removed":reason==="NR"?"Marked not relevant":"Marked not wanted");render()}catch(error){console.error("V6 feedback save failed:",error);showToast("Feedback was not saved");card.querySelectorAll("[data-feedback]").forEach(btn=>btn.disabled=false)}});
locationButton.addEventListener("click",()=>setLocation(true));
document.addEventListener("visibilitychange",()=>{if(!document.hidden){updateClock();updateWeather();refreshIfChanged();refreshNflLive()}});
async function start(){await loadData(true);setLocation(false);updateClock();setInterval(updateClock,1000);setInterval(()=>{if(Date.now()>=nextCheck)refreshIfChanged();updateWeather()},15000);setInterval(refreshNflLive,30000)}
start().catch(error=>{console.error("V6 startup failed:",error);health.textContent="V6 startup error";root.innerHTML='<div class="empty">The V6 build could not start.</div>'});