from pathlib import Path
import re

path = Path("index.html")
text = path.read_text(encoding="utf-8")

# The visual theme lives in external stylesheets. Remove every legacy
# stylesheet generated by the old design pipeline, including the anonymous
# legacy <style> block that had no id and was therefore escaping cleanup.
for marker in ('<style id="clean-news-v1">', '<style id="article-style-v1">', '<style id="load-more-style-v1">'):
    while marker in text:
        start = text.find(marker)
        end = text.find('</style>', start)
        if end == -1:
            break
        text = text[:start] + text[end + len('</style>'):]

legacy_start = text.find('<style>\n:root{--ink:#101828;')
if legacy_start != -1:
    legacy_end = text.find('</style>', legacy_start)
    if legacy_end != -1:
        text = text[:legacy_start] + text[legacy_end + len('</style>'):]

# Prevent duplicate external theme/header links.
for href in ('styles/theme.css', 'styles/header.css'):
    text = re.sub(r'<link\s+rel=["\']stylesheet["\']\s+href=["\']' + re.escape(href) + r'(?:\?[^"\']*)?["\']\s*/?>\s*', '', text, flags=re.I)

links = '<link rel="stylesheet" href="styles/theme.css?v=3">\n<link rel="stylesheet" href="styles/header.css?v=1">'
text = text.replace('</head>', links + '\n</head>', 1)

path.write_text(text, encoding="utf-8")
print('Applied authoritative Underreported theme, editorial header, and removed legacy visual CSS.')
