from pathlib import Path
import re

path = Path("index.html")
text = path.read_text(encoding="utf-8")

# The visual theme lives only in styles/theme.css. Remove every legacy
# stylesheet generated by the old design pipeline, including the anonymous
# legacy <style> block that had no id and was therefore escaping cleanup.
for marker in ('<style id="clean-news-v1">', '<style id="article-style-v1">', '<style id="load-more-style-v1">'):
    while marker in text:
        start = text.find(marker)
        end = text.find('</style>', start)
        if end == -1:
            break
        text = text[:start] + text[end + len('</style>'):]

# Remove the old anonymous generated stylesheet. It begins with the legacy
# --ink/--muted variables and must not remain after the external theme link.
legacy_start = text.find('<style>\n:root{--ink:#101828;')
if legacy_start != -1:
    legacy_end = text.find('</style>', legacy_start)
    if legacy_end != -1:
        text = text[:legacy_start] + text[legacy_end + len('</style>'):]

# Prevent duplicate external theme links and bump the cache key whenever this
# authoritative stylesheet is rebuilt.
link = '<link rel="stylesheet" href="styles/theme.css?v=3">'
text = re.sub(r'<link\s+rel=["\']stylesheet["\']\s+href=["\']styles/theme\.css(?:\?[^"\']*)?["\']\s*/?>\s*', '', text, flags=re.I)
text = text.replace('</head>', link + '\n</head>', 1)

path.write_text(text, encoding="utf-8")
print('Applied authoritative Underreported theme and removed all legacy visual CSS.')
