from pathlib import Path

path = Path("index.html")
text = path.read_text(encoding="utf-8")
old = "const sections=[['top','🔴 Top Stories','#dc2626'],['underreported','🟣 Underreported','#7c3aed'],['world','🌎 World','#2563eb'],['us','🇺🇸 United States','#1e3a8a'],['presidential','🏛️ Presidential','#b45309'],['federal','🏛️ Federal Government','#ca8a04'],['nm','🏜️ New Mexico','#0f766e'],['local','📍 Local / Four Corners','#15803d'],['technology','💻 Technology','#0891b2'],['gaming','🎮 Gaming & Computing','#7c3aed'],['military','⚔️ Military & War','#991b1b']];"
new = "const sections=[['top','🔴 Top Stories','#dc2626'],['nfl','🏈 NFL','#166534'],['underreported','🟣 Underreported','#7c3aed'],['world','🌎 World','#2563eb'],['us','🇺🇸 United States','#1e3a8a'],['presidential','🏛️ Presidential','#b45309'],['federal','🏛️ Federal Government','#ca8a04'],['nm','🏜️ New Mexico','#0f766e'],['local','📍 Local / Four Corners','#15803d'],['region','🌎 Region','#2563eb'],['technology','💻 Technology','#0891b2'],['gaming','🎮 Gaming & Computing','#7c3aed'],['military','⚔️ Military & War','#991b1b']];"
text = text.replace(old,new,1)
marker='<script id="region-tab-v1">'
while marker in text:
    s=text.find(marker); e=text.find('</script>',s)
    if e<0: break
    text=text[:s]+text[e+9:]
script=r'''<script id="region-tab-v1">
let detectedRegion=localStorage.getItem('underreported-region')||'southwest',detectedLocation=localStorage.getItem('underreported-location')||'';
const regionLabels={southwest:'Southwest',west:'West',mountain:'Mountain West',midwest:'Midwest',south:'South',northeast:'Northeast','pacific-northwest':'Pacific Northwest',southeast:'Southeast'};
const stateRegion={AZ:'southwest',NM:'southwest',UT:'southwest',CO:'southwest',CA:'west',NV:'west',HI:'west',ID:'mountain',MT:'mountain',WY:'mountain',IL:'midwest',IN:'midwest',MI:'midwest',OH:'midwest',WI:'midwest',MN:'midwest',IA:'midwest',MO:'midwest',KS:'midwest',NE:'midwest',SD:'midwest',ND:'midwest',TX:'south',OK:'south',AR:'south',LA:'south',TN:'south',KY:'south',VA:'south',WV:'south',MD:'south',DE:'south',NY:'northeast',PA:'northeast',NJ:'northeast',CT:'northeast',RI:'northeast',MA:'northeast',VT:'northeast',NH:'northeast',ME:'northeast',DC:'northeast',WA:'pacific-northwest',OR:'pacific-northwest',AK:'pacific-northwest',FL:'southeast',GA:'southeast',AL:'southeast',SC:'southeast',NC:'southeast',MS:'southeast'};
function renderNfl(){
 const root=document.getElementById('news-feed');root.innerHTML='';const sec=document.createElement('section');sec.className='section';sec.style.setProperty('--accent','#166534');
 const h=document.createElement('div');h.className='section-header';h.innerHTML='<h2>🏈 NFL</h2><span class="count">Live scores & latest news</span>';sec.appendChild(h);
 const body=document.createElement('div');body.className='section-body';body.innerHTML='<div class="loading">Loading NFL scores…</div>';sec.appendChild(body);root.appendChild(sec);
 fetch('https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?limit=32',{cache:'no-store'}).then(r=>r.json()).then(d=>{body.innerHTML='';(d.events||[]).forEach(ev=>{const c=ev.competitions?.[0],ts=c?.competitors||[],a=ts.find(t=>t.homeAway==='away'),h=ts.find(t=>t.homeAway==='home'),card=document.createElement('article');card.className='news-item';card.innerHTML=`<h3>${esc(a?.team?.displayName||'Away')} <strong>${esc(a?.score??'-')}</strong> @ ${esc(h?.team?.displayName||'Home')} <strong>${esc(h?.score??'-')}</strong></h3><div class="meta"><span>${esc(ev.status?.type?.state==='post'?'FINAL':ev.status?.type?.shortDetail||ev.status?.type?.detail||'Scheduled')}</span></div>`;body.appendChild(card)});if(!d.events?.length)body.innerHTML='<div class="empty">No NFL games currently scheduled.</div>'}).catch(()=>body.innerHTML='<div class="empty">NFL scores are temporarily unavailable.</div>');
 const news=allItems.filter(x=>(x.querySelector('category')?.textContent?.trim()||'')==='nfl').slice(0,10);if(news.length){const nh=document.createElement('div');nh.className='section-header';nh.style.marginTop='28px';nh.innerHTML='<h2>NFL News</h2><span class="count">Latest</span>';root.appendChild(nh);const nb=document.createElement('div');nb.className='section-body';news.forEach((item,i)=>{const ar=document.createElement('article');ar.className='news-item';const title=item.querySelector('title')?.textContent||'Untitled',link=item.querySelector('link')?.textContent||'#',desc=item.querySelector('description')?.textContent||'',source=item.querySelector('source')?.textContent||'';ar.innerHTML=`<h3><a href="${esc(link)}" target="_blank" rel="noopener noreferrer">${i+1}. ${esc(title)}</a></h3>${desc?`<p class="description">${esc(desc)}</p>`:''}<div class="meta">${source?`<span class="source">${esc(source)}</span>`:''}</div>`;nb.appendChild(ar)});root.appendChild(nb)}
}
function regionRender(items){if(active==='nfl'){renderNfl();return}const def=sections.find(x=>x[0]===active),accent=def?def[2]:'#111827';let list=items.filter(x=>(x.querySelector('category')?.textContent?.trim()||'world')===active);if(active==='region')list=list.filter(x=>(x.querySelector('region')?.textContent?.trim()||'')===detectedRegion);const root=document.getElementById('news-feed');root.innerHTML='';const sec=document.createElement('section');sec.className='section';sec.style.setProperty('--accent',accent);const head=document.createElement('div');head.className='section-header';const label=active==='region'?'🌎 '+regionLabels[detectedRegion]+' Region':(def?def[1]:'News');head.innerHTML=`<h2>${esc(label)}</h2><span class="count">${list.length} stories</span>`;sec.appendChild(head);const body=document.createElement('div');body.className='section-body';if(!list.length)body.innerHTML='<div class="empty">No stories available right now.</div>';list.forEach((item,i)=>{const ar=document.createElement('article');ar.className='news-item';const title=item.querySelector('title')?.textContent||'Untitled',desc=item.querySelector('description')?.textContent||'',why=item.querySelector('whyMatters')?.textContent||'',link=item.querySelector('link')?.textContent||'#',date=item.querySelector('pubDate')?.textContent||'',source=item.querySelector('source')?.textContent||'';ar.innerHTML=`<h3><a href="${esc(link)}" target="_blank" rel="noopener noreferrer">${i+1}. ${esc(title)}</a></h3>${desc?`<p class="description">${esc(desc)}</p>`:''}${why?`<div class="why">${esc(why)}</div>`:''}<div class="meta"><span>${esc(formatDate(date))}</span>${source?`<span class="source">${esc(source)}</span>`:''}</div>`;body.appendChild(ar)});sec.appendChild(body);root.appendChild(sec)}
render=regionRender;
buildTabs=function(){const tabs=document.getElementById('tabs');tabs.innerHTML='';sections.forEach(([key,label,accent])=>{const b=document.createElement('button');b.className='tab'+(key===active?' active':'');b.textContent=key==='region'&&detectedLocation?'🌎 '+regionLabels[detectedRegion]:label;b.onclick=async()=>{active=key;localStorage.setItem('underreported-active-tab',active);buildTabs();if(key==='region')await detectUserRegion();render(allItems)};b.style.setProperty('--accent',accent);tabs.appendChild(b)})};
async function detectUserRegion(){try{let c;if(navigator.geolocation)c=await new Promise((r,j)=>navigator.geolocation.getCurrentPosition(r,j,{timeout:8000,maximumAge:300000}));const p=new URLSearchParams({localityLanguage:'en'});if(c){p.set('latitude',c.coords.latitude);p.set('longitude',c.coords.longitude)}const d=await fetch('https://api.bigdatacloud.net/data/reverse-geocode-client?'+p,{cache:'no-store'}).then(r=>r.json()),code=(d.principalSubdivisionCode||'').replace(/^US-/,'').toUpperCase();if(stateRegion[code])detectedRegion=stateRegion[code];detectedLocation=[d.city,d.principalSubdivisionCode?.replace(/^US-/,'')].filter(Boolean).join(', ');localStorage.setItem('underreported-region',detectedRegion);localStorage.setItem('underreported-location',detectedLocation);buildTabs();if(active==='region')render(allItems)}catch(e){buildTabs()}}
detectUserRegion();
</script>'''
text=text.replace('</body>',script+'</body>',1)
path.write_text(text,encoding='utf-8')
print('Added NFL tab after Top Stories with live scores and NFL news.')
